#
# This file is autogenerated on every push of files in '.github/data'
#

name: Manifest workflow

# Controls when the action will run. Triggers the workflow on push or pull request events but
# only for the main branch
on: repository_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      {{ACTIONS}}
