name: Update manifest workflow

# Controls when the action will run. Triggers the workflow on push or pull request events but
# only for the main branch
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      # Trigger on change in following path
      - '.github/data/**'
      # Doesn't trigger when these files change
      - '!.github/workflows/update-manifest-workflow.yml'
      - '!.github/workflows/update-manifest.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT_TOKEN }}
      - name: Build update-manifest-workflow_01.yml
        run: python ${{ github.workspace }}/.github/scripts/update-manifest-workflow_01.py
      - name: Get current date
        id: get-current-date
        run: echo "::set-output name=date::$(date '+%d/%m/%Y')"
        shell: bash
      - uses: EndBug/add-and-commit@v5
        with:
          author_name: Marc Proux
          author_email: marc.proux@outlook.fr
          message: "[${{ steps.get-current-date.outputs.date }}] Manifest workflow update"
          add: ".github/workflows/update-manifest.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Trigger manifest repository
        run: |
          curl -XPOST \
          -u "${{ secrets.PAT_USERNAME }}:${{ secrets.PAT_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${{ secrets.MANIFEST_REPOSITORY }}/dispatches \
          --data '{"event_type": "build_application"}'
